### PR TITLE
Add Device "Cisco Nexus"

### PR DESCRIPTION
**Pull request by seppeel**
This will add the device "Cisco Nexus" when routerconfigs is installed.

### CODE REVIEW

**Review by netniV — APPROVED** [review]
Looks good to me.  We should probably try and get more device types added to make life easier as a starting point.

**Comment by seppeel** [comment]
like already mentioned in issue #33 i have IBM  Flex System i could try to add.
But we will run into problems because the hostname is in this format:
hostname "<hostname>"
(with ""). This will destroy the hostname after backup.
a workaround would be, to add an option for device types "Hostname in quotation marks in config file"

**Comment by netniV** [comment]
Can you open a separate issue for that, and we can see what we can do for it 👍

**Comment by seppeel** [comment]
i didnt properly take over my own changes to the PR and created a syntax error. #46 should be merged to fix that.

**Pull request merged**
